version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./php
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true


  phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - "8081:80"
      links:
        - database:database
      depends_on:
        - database
      restart: always
      environment:
        PMA_HOSTS: database

  database:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_db
    volumes:
      - ./mysql:/var/lib/mysql